/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mr_jni_Image_jni */

#ifndef _Included_mr_jni_Image_jni
#define _Included_mr_jni_Image_jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mr_jni_Image_jni
 * Method:    predictImage
 * Signature: (Lmr/jni/ImageContainer;Lmr/jni/Result;)V
 */
JNIEXPORT void JNICALL Java_mr_jni_Image_1jni_predictImage
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
